version: '3.7'

services:
  valheim:
    container_name: valheim_server
    image: valheim_server
    build:
      context: .
    volumes:
      - './data:/home/steam/valheim/data'
    ports:
      - '2456:2456/udp'
      - '2457:2457/udp'
      - '2458:2458/udp'
    environment:
      - SERVER_NAME=Dedicated
      - SERVER_PORT=2456
      - SERVER_PASSWORD
      - SERVER_WORLD=Dedicated
      # - UPDATE=1
